### PR TITLE
fix: 🐛 route payload options missing types

### LINKED ISSUE #4505: I cannot get any types
### Runtime

node

### Runtime version

v20

### Module version

"^20.1.4",

### Last module version without issue

_No response_

### Used with

_No response_

### Any other relevant information

_No response_

### What are you trying to achieve or the steps to reproduce?

```
import { Request, ResponseToolkit } from '@hapi/hapi';
```

lets me import but `ResponseToolkit` is just any.

### What was the result you got?

`any`

### What result did you expect?

a real type

### PR DESCRIPTION
**Pull request by damusix**
🎟️ Fixes #4505 #4501

Additionally adds missing method cache typings to select cache name and segment name

### CODE REVIEW

File: test/types/index.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { types as lab } from '@hapi/lab';
 import { expect } from '@hapi/code';
+import * as CatboxMemory from '@hapi/catbox-memory';
```
Comment (damusix) [inline test/types/index.ts:3]: Dependent on https://github.com/hapijs/catbox-memory/pull/90 for tests to pass

**Review by Nargonath — APPROVED** [review]
Code LGTM. We'll see how the tests looks once the dependent PR is merged and deployed.

File: lib/types/route.d.ts [hunk 2]
```diff
@@ -255,6 +255,13 @@ export interface RouteOptionsPayload {
      */
     maxBytes?: number | undefined;
 
+    /**
+     * @default 1000
+     * Limits the size of incoming payloads to the specified byte count. Allowing very large payloads may cause the server to run out of memory.
```
Comment (kanongil) [inline lib/types/route.d.ts:260]: Description is wrong. From API docs:

```
Limits the number of parts allowed in multipart payloads.
```

Comment (damusix) [reply lib/types/route.d.ts:260]: Wrong copy paste haha
